vich_uploader:
    db_driver: orm

    mappings:
        animal_image:
            uri_prefix: /IMG
            upload_destination: '%kernel.project_dir%/public/IMG'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
